# OMPL 规划器配置
planner_configs:
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.0
  RRTkConfigDefault:
    type: geometric::RRT
    range: 0.0
    goal_bias: 0.05
  RRTstarkConfigDefault:
    type: geometric::RRTstar
    range: 0.0
    goal_bias: 0.05
    delay_collision_checking: 1
  ESTkConfigDefault:
    type: geometric::EST
    range: 0.0
    goal_bias: 0.05

arm:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - RRTConnectkConfigDefault
    - RRTkConfigDefault
    - RRTstarkConfigDefault
    - ESTkConfigDefault
  projection_evaluator: joints(base_yaw_joint,arm_lift_joint,wrist_pitch_joint)
  longest_valid_segment_fraction: 0.005
  allowed_planning_time: 1.0

gripper:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - RRTConnectkConfigDefault
  projection_evaluator: joints(left_finger_joint,right_finger_joint)
  longest_valid_segment_fraction: 0.005
  allowed_planning_time: 0.5
